api:
  gateway:
    endpoints:
      0:
        path: /accounts/**
        method: GET
        location: http://${accounts.queryside.service.host}:8080
      1:
        path: /accounts/**
        method: POST
        location: http://${accounts.commandside.service.host}:8080
      2:
        path: /customers/**
        method: GET
        location: http://${customers.queryside.service.host}:8080
      3:
        path: /customers/**
        method: POST
        location: http://${customers.commandside.service.host}:8080
      4:
        path: /transfers/**
        method: POST
        location: http://${transfers.commandside.service.host}:8080